---
name: debian10

on:
  pull_request:
  push:
    paths:
      - 'debian10/**'
      - '.github/workflows/debian10.yml'
  schedule:
    - cron: '10 6,15 * * 1,6'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test debian10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Test building image.
        run: cd debian10 && docker build -t debian10 .

      - name: Run the built image.
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro debian10

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    # needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4.1.1
      - uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: buluma/setup-buildx-action@0.1.0
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v5.3.0
        with:
          context: debian10/
          file: debian10/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.repository }}:debian10, ${{ github.repository }}:buster
