---
name: kali-rolling

on:
  pull_request:
  push:
    paths:
      - 'kali/**'
      - '.github/workflows/kali.yml'
  schedule:
    - cron: '10 6,15 * * 1,6'
  workflow_dispatch:

permissions: write-all

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test kali
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v2.6.0

      - name: Test building image.
        run: cd kali && docker build -t kali .

      - name: Run the built image.
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro kali

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: kali/
          file: kali/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ github.repository }}:kali
