---
name: ubuntu2004

on:
  pull_request:
  push:
    paths:
      - 'ubuntu2004/**'
      - '.github/workflows/ubuntu2004.yml'
  schedule:
    - cron: '10 6,15 * * 1,6'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test ubuntu2004
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: cd ubuntu2004 && docker build -t ubuntu2004 .

      - name: Run the built image.
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro ubuntu2004

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    # needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: buluma/setup-buildx-action@0.1.0
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ubuntu2004/
          file: ubuntu2004/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.repository }}:ubuntu2004
